api_version: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitoring
  creation_timestamp: '2024-11-29T06:58:04+00:00'
  deletion_grace_period_seconds: null
  deletion_timestamp: null
  finalizers: null
  generate_name: null
  generation: 1
  labels:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/version: 0.27.0
    helm.sh/chart: prometheus-1.3.28
  managed_fields:
  - api_version: apps/v1
    fields_type: FieldsV1
    fields_v1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec:
        f:persistentVolumeClaimRetentionPolicy:
          .: {}
          f:whenDeleted: {}
          f:whenScaled: {}
        f:podManagementPolicy: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:serviceName: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app.kubernetes.io/component: {}
              f:app.kubernetes.io/instance: {}
              f:app.kubernetes.io/managed-by: {}
              f:app.kubernetes.io/name: {}
              f:app.kubernetes.io/part-of: {}
              f:app.kubernetes.io/version: {}
              f:helm.sh/chart: {}
          f:spec:
            f:affinity:
              .: {}
              f:podAntiAffinity:
                .: {}
                f:preferredDuringSchedulingIgnoredDuringExecution: {}
            f:automountServiceAccountToken: {}
            f:containers:
              k:{"name":"alertmanager"}:
                .: {}
                f:args: {}
                f:env:
                  .: {}
                  k:{"name":"POD_IP"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:fieldRef: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:livenessProbe:
                  .: {}
                  f:failureThreshold: {}
                  f:httpGet:
                    .: {}
                    f:path: {}
                    f:port: {}
                    f:scheme: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":9093,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":9094,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":9094,"protocol":"UDP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:readinessProbe:
                  .: {}
                  f:failureThreshold: {}
                  f:httpGet:
                    .: {}
                    f:path: {}
                    f:port: {}
                    f:scheme: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:resources:
                  .: {}
                  f:limits:
                    .: {}
                    f:cpu: {}
                    f:ephemeral-storage: {}
                    f:memory: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:ephemeral-storage: {}
                    f:memory: {}
                f:securityContext:
                  .: {}
                  f:allowPrivilegeEscalation: {}
                  f:capabilities:
                    .: {}
                    f:drop: {}
                  f:privileged: {}
                  f:readOnlyRootFilesystem: {}
                  f:runAsGroup: {}
                  f:runAsNonRoot: {}
                  f:runAsUser: {}
                  f:seLinuxOptions: {}
                  f:seccompProfile:
                    .: {}
                    f:type: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/bitnami/alertmanager/data"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"/opt/bitnami/alertmanager/conf"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:readOnly: {}
                  k:{"mountPath":"/tmp"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:subPath: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext:
              .: {}
              f:fsGroup: {}
              f:fsGroupChangePolicy: {}
            f:serviceAccount: {}
            f:serviceAccountName: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"config"}:
                .: {}
                f:configMap:
                  .: {}
                  f:defaultMode: {}
                  f:name: {}
                f:name: {}
              k:{"name":"data"}:
                .: {}
                f:emptyDir: {}
                f:name: {}
              k:{"name":"empty-dir"}:
                .: {}
                f:emptyDir: {}
                f:name: {}
        f:updateStrategy:
          f:type: {}
    manager: helm
    operation: Update
    subresource: null
    time: '2024-11-29T06:58:04+00:00'
  - api_version: apps/v1
    fields_type: FieldsV1
    fields_v1:
      f:status:
        f:availableReplicas: {}
        f:collisionCount: {}
        f:currentReplicas: {}
        f:currentRevision: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updateRevision: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: '2024-11-29T06:58:34+00:00'
  name: prometheus-alertmanager
  namespace: monitoring
  owner_references: null
  resource_version: '937157'
  self_link: null
  uid: bdf9e9b1-dd80-4db2-a486-fa6de92f9bfe
spec:
  min_ready_seconds: null
  ordinals: null
  persistent_volume_claim_retention_policy:
    when_deleted: Retain
    when_scaled: Retain
  pod_management_policy: OrderedReady
  replicas: 1
  revision_history_limit: 10
  selector:
    match_expressions: null
    match_labels:
      app.kubernetes.io/component: alertmanager
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: prometheus
  service_name: prometheus-alertmanager-headless
  template:
    metadata:
      annotations: null
      creation_timestamp: null
      deletion_grace_period_seconds: null
      deletion_timestamp: null
      finalizers: null
      generate_name: null
      generation: null
      labels:
        app.kubernetes.io/component: alertmanager
        app.kubernetes.io/instance: prometheus
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: prometheus
        app.kubernetes.io/part-of: prometheus
        app.kubernetes.io/version: 0.27.0
        helm.sh/chart: prometheus-1.3.28
      managed_fields: null
      name: null
      namespace: null
      owner_references: null
      resource_version: null
      self_link: null
      uid: null
    spec:
      active_deadline_seconds: null
      affinity:
        node_affinity: null
        pod_affinity: null
        pod_anti_affinity:
          preferred_during_scheduling_ignored_during_execution:
          - pod_affinity_term:
              label_selector:
                match_expressions: null
                match_labels:
                  app.kubernetes.io/component: alertmanager
                  app.kubernetes.io/instance: prometheus
                  app.kubernetes.io/name: prometheus
              match_label_keys: null
              mismatch_label_keys: null
              namespace_selector: null
              namespaces: null
              topology_key: kubernetes.io/hostname
            weight: 1
          required_during_scheduling_ignored_during_execution: null
      automount_service_account_token: false
      containers:
      - args:
        - --config.file=/opt/bitnami/alertmanager/conf/alertmanager.yaml
        - --storage.path=/opt/bitnami/alertmanager/data
        - --web.listen-address=0.0.0.0:9093
        command: null
        env:
        - name: POD_IP
          value: null
          value_from:
            config_map_key_ref: null
            field_ref:
              api_version: v1
              field_path: status.podIP
            resource_field_ref: null
            secret_key_ref: null
        env_from: null
        image: docker.io/bitnami/alertmanager:0.27.0-debian-12-r26
        image_pull_policy: IfNotPresent
        lifecycle: null
        liveness_probe:
          _exec: null
          failure_threshold: 3
          grpc: null
          http_get:
            host: null
            http_headers: null
            path: /-/healthy
            port: http
            scheme: HTTP
          initial_delay_seconds: 5
          period_seconds: 20
          success_threshold: 1
          tcp_socket: null
          termination_grace_period_seconds: null
          timeout_seconds: 3
        name: alertmanager
        ports:
        - container_port: 9093
          host_ip: null
          host_port: null
          name: http
          protocol: TCP
        - container_port: 9094
          host_ip: null
          host_port: null
          name: tcp-cluster
          protocol: TCP
        - container_port: 9094
          host_ip: null
          host_port: null
          name: udp-cluster
          protocol: UDP
        readiness_probe:
          _exec: null
          failure_threshold: 5
          grpc: null
          http_get:
            host: null
            http_headers: null
            path: /-/ready
            port: http
            scheme: HTTP
          initial_delay_seconds: 5
          period_seconds: 10
          success_threshold: 1
          tcp_socket: null
          termination_grace_period_seconds: null
          timeout_seconds: 2
        resize_policy: null
        resources:
          claims: null
          limits:
            cpu: 150m
            ephemeral-storage: 2Gi
            memory: 192Mi
          requests:
            cpu: 100m
            ephemeral-storage: 50Mi
            memory: 128Mi
        restart_policy: null
        security_context:
          allow_privilege_escalation: false
          app_armor_profile: null
          capabilities:
            add: null
            drop:
            - ALL
          privileged: false
          proc_mount: null
          read_only_root_filesystem: true
          run_as_group: 1001
          run_as_non_root: true
          run_as_user: 1001
          se_linux_options:
            level: null
            role: null
            type: null
            user: null
          seccomp_profile:
            localhost_profile: null
            type: RuntimeDefault
          windows_options: null
        startup_probe: null
        stdin: null
        stdin_once: null
        termination_message_path: /dev/termination-log
        termination_message_policy: File
        tty: null
        volume_devices: null
        volume_mounts:
        - mount_path: /tmp
          mount_propagation: null
          name: empty-dir
          read_only: null
          recursive_read_only: null
          sub_path: tmp-dir
          sub_path_expr: null
        - mount_path: /opt/bitnami/alertmanager/conf
          mount_propagation: null
          name: config
          read_only: true
          recursive_read_only: null
          sub_path: null
          sub_path_expr: null
        - mount_path: /bitnami/alertmanager/data
          mount_propagation: null
          name: data
          read_only: null
          recursive_read_only: null
          sub_path: null
          sub_path_expr: null
        working_dir: null
      dns_config: null
      dns_policy: ClusterFirst
      enable_service_links: null
      ephemeral_containers: null
      host_aliases: null
      host_ipc: null
      host_network: null
      host_pid: null
      host_users: null
      hostname: null
      image_pull_secrets: null
      init_containers: null
      node_name: null
      node_selector: null
      os: null
      overhead: null
      preemption_policy: null
      priority: null
      priority_class_name: null
      readiness_gates: null
      resource_claims: null
      restart_policy: Always
      runtime_class_name: null
      scheduler_name: default-scheduler
      scheduling_gates: null
      security_context:
        app_armor_profile: null
        fs_group: 1001
        fs_group_change_policy: Always
        run_as_group: null
        run_as_non_root: null
        run_as_user: null
        se_linux_options: null
        seccomp_profile: null
        supplemental_groups: null
        supplemental_groups_policy: null
        sysctls: null
        windows_options: null
      service_account: prometheus-alertmanager
      service_account_name: prometheus-alertmanager
      set_hostname_as_fqdn: null
      share_process_namespace: null
      subdomain: null
      termination_grace_period_seconds: 30
      tolerations: null
      topology_spread_constraints: null
      volumes:
      - aws_elastic_block_store: null
        azure_disk: null
        azure_file: null
        cephfs: null
        cinder: null
        config_map: null
        csi: null
        downward_api: null
        empty_dir:
          medium: null
          size_limit: null
        ephemeral: null
        fc: null
        flex_volume: null
        flocker: null
        gce_persistent_disk: null
        git_repo: null
        glusterfs: null
        host_path: null
        image: null
        iscsi: null
        name: empty-dir
        nfs: null
        persistent_volume_claim: null
        photon_persistent_disk: null
        portworx_volume: null
        projected: null
        quobyte: null
        rbd: null
        scale_io: null
        secret: null
        storageos: null
        vsphere_volume: null
      - aws_elastic_block_store: null
        azure_disk: null
        azure_file: null
        cephfs: null
        cinder: null
        config_map:
          default_mode: 420
          items: null
          name: prometheus-alertmanager
          optional: null
        csi: null
        downward_api: null
        empty_dir: null
        ephemeral: null
        fc: null
        flex_volume: null
        flocker: null
        gce_persistent_disk: null
        git_repo: null
        glusterfs: null
        host_path: null
        image: null
        iscsi: null
        name: config
        nfs: null
        persistent_volume_claim: null
        photon_persistent_disk: null
        portworx_volume: null
        projected: null
        quobyte: null
        rbd: null
        scale_io: null
        secret: null
        storageos: null
        vsphere_volume: null
      - aws_elastic_block_store: null
        azure_disk: null
        azure_file: null
        cephfs: null
        cinder: null
        config_map: null
        csi: null
        downward_api: null
        empty_dir:
          medium: null
          size_limit: null
        ephemeral: null
        fc: null
        flex_volume: null
        flocker: null
        gce_persistent_disk: null
        git_repo: null
        glusterfs: null
        host_path: null
        image: null
        iscsi: null
        name: data
        nfs: null
        persistent_volume_claim: null
        photon_persistent_disk: null
        portworx_volume: null
        projected: null
        quobyte: null
        rbd: null
        scale_io: null
        secret: null
        storageos: null
        vsphere_volume: null
  update_strategy:
    rolling_update: null
    type: RollingUpdate
  volume_claim_templates: null
status:
  available_replicas: 1
  collision_count: 0
  conditions: null
  current_replicas: 1
  current_revision: prometheus-alertmanager-6d86878f47
  observed_generation: 1
  ready_replicas: 1
  replicas: 1
  update_revision: prometheus-alertmanager-6d86878f47
  updated_replicas: 1
