apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2024-11-17T05:50:31+00:00","deletionGracePeriodSeconds":null,"deletionTimestamp":null,"finalizers":null,"generateName":null,"generation":null,"labels":{"component":"apiserver","provider":"kubernetes"},"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:component":{},"f:provider":{}}},"f:spec":{"f:internalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":443,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{}}},"f:sessionAffinity":{},"f:type":{}}},"manager":"kube-apiserver","operation":"Update","subresource":null,"time":"2024-11-17T05:50:31+00:00"},{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{"f:ports":{"k:{\"port\":443,\"protocol\":\"TCP\"}":{"f:targetPort":{}}}}},"manager":"OpenAPI-Generator","operation":"Update","subresource":null,"time":"2024-11-19T03:40:39+00:00"}],"name":"kubernetes","namespace":"default","ownerReferences":null,"resourceVersion":"159556","selfLink":null,"uid":"b259c311-d0a2-49dd-b20a-385130bcf56d"},"spec":{"allocateLoadBalancerNodePorts":null,"clusterIPs":["10.96.0.1"],"clusterIp":"10.96.0.1","externalIPs":null,"externalName":null,"externalTrafficPolicy":null,"healthCheckNodePort":null,"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","loadBalancerClass":null,"loadBalancerIp":null,"loadBalancerSourceRanges":null,"ports":[{"appProtocol":null,"name":"https","nodePort":null,"port":443,"protocol":"TCP","targetPort":443}],"publishNotReadyAddresses":null,"selector":null,"sessionAffinity":"None","sessionAffinityConfig":null,"trafficDistribution":null,"type":"ClusterIP"},"status":{"conditions":null,"loadBalancer":{"ingress":null}}}

      '
  creationTimestamp: '2024-11-17T05:50:31+00:00'
  labels:
    component: apiserver
    provider: kubernetes
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:component: {}
          f:provider: {}
      f:spec:
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":443,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kube-apiserver
    operation: Update
    time: '2024-11-17T05:50:31+00:00'
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:ports:
          k:{"port":443,"protocol":"TCP"}:
            f:targetPort: {}
    manager: OpenAPI-Generator
    operation: Update
    time: '2024-11-19T03:40:39+00:00'
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: '2024-11-20T16:28:27+00:00'
  name: kubernetes
  namespace: default
  resourceVersion: '272917'
  uid: b259c311-d0a2-49dd-b20a-385130bcf56d
spec:
  clusterIP: 10.96.0.1
  clusterIPs:
  - 10.96.0.1
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
