apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"meta.helm.sh/release-name":"ghost-1731881169","meta.helm.sh/release-namespace":"default","pv.kubernetes.io/bind-completed":"yes","pv.kubernetes.io/bound-by-controller":"yes","volume.beta.kubernetes.io/storage-provisioner":"docker.io/hostpath","volume.kubernetes.io/storage-provisioner":"docker.io/hostpath"},"creationTimestamp":"2024-11-17T22:06:12+00:00","deletionGracePeriodSeconds":null,"deletionTimestamp":null,"finalizers":["kubernetes.io/pvc-protection"],"generateName":null,"generation":null,"labels":{"app":"ghost-1731881169","app.kubernetes.io/managed-by":"Helm","chart":"ghost-9.1.13","heritage":"Helm","release":"ghost-1731881169"},"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:meta.helm.sh/release-name":{},"f:meta.helm.sh/release-namespace":{}},"f:labels":{".":{},"f:app":{},"f:app.kubernetes.io/managed-by":{},"f:chart":{},"f:heritage":{},"f:release":{}}},"f:spec":{"f:accessModes":{},"f:resources":{"f:requests":{".":{},"f:storage":{}}},"f:volumeMode":{}}},"manager":"helm","operation":"Update","subresource":null,"time":"2024-11-17T22:06:12+00:00"},{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:pv.kubernetes.io/bind-completed":{},"f:pv.kubernetes.io/bound-by-controller":{},"f:volume.beta.kubernetes.io/storage-provisioner":{},"f:volume.kubernetes.io/storage-provisioner":{}}},"f:spec":{"f:volumeName":{}}},"manager":"kube-controller-manager","operation":"Update","subresource":null,"time":"2024-11-17T22:06:12+00:00"},{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:accessModes":{},"f:capacity":{".":{},"f:storage":{}},"f:phase":{}}},"manager":"kube-controller-manager","operation":"Update","subresource":"status","time":"2024-11-17T22:06:12+00:00"},{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:kubectl.kubernetes.io/last-applied-configuration":{}}}},"manager":"kubectl-client-side-apply","operation":"Update","subresource":null,"time":"2024-11-19T21:37:33+00:00"}],"name":"ghost-1731881169","namespace":"default","ownerReferences":null,"resourceVersion":"220861","selfLink":null,"uid":"003bb9de-b98a-4bb0-9f7a-3d18ad9d6237"},"spec":{"accessModes":["ReadWriteOnce"],"dataSource":null,"dataSourceRef":null,"resources":{"limits":null,"requests":{"storage":"8Gi"}},"selector":null,"storageClassName":"hostpath","volumeAttributesClassName":null,"volumeMode":"Filesystem","volumeName":"pvc-003bb9de-b98a-4bb0-9f7a-3d18ad9d6237"},"status":{"accessModes":["ReadWriteOnce"],"allocatedResourceStatuses":null,"allocatedResources":null,"capacity":{"storage":"8Gi"},"conditions":null,"currentVolumeAttributesClassName":null,"modifyVolumeStatus":null,"phase":"Bound"}}

      '
    meta.helm.sh/release-name: ghost-1731881169
    meta.helm.sh/release-namespace: default
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: docker.io/hostpath
    volume.kubernetes.io/storage-provisioner: docker.io/hostpath
  creationTimestamp: '2024-11-17T22:06:12+00:00'
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: ghost-1731881169
    app.kubernetes.io/managed-by: Helm
    chart: ghost-9.1.13
    heritage: Helm
    release: ghost-1731881169
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:heritage: {}
          f:release: {}
      f:spec:
        f:accessModes: {}
        f:resources:
          f:requests:
            .: {}
            f:storage: {}
        f:volumeMode: {}
    manager: helm
    operation: Update
    time: '2024-11-17T22:06:12+00:00'
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:pv.kubernetes.io/bind-completed: {}
          f:pv.kubernetes.io/bound-by-controller: {}
          f:volume.beta.kubernetes.io/storage-provisioner: {}
          f:volume.kubernetes.io/storage-provisioner: {}
      f:spec:
        f:volumeName: {}
    manager: kube-controller-manager
    operation: Update
    time: '2024-11-17T22:06:12+00:00'
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:accessModes: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:phase: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: '2024-11-17T22:06:12+00:00'
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: '2024-11-20T04:38:51+00:00'
  name: ghost-1731881169
  namespace: default
  resourceVersion: '247721'
  uid: 003bb9de-b98a-4bb0-9f7a-3d18ad9d6237
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: hostpath
  volumeMode: Filesystem
  volumeName: pvc-003bb9de-b98a-4bb0-9f7a-3d18ad9d6237
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound
