apiVersion: v1
data:
  mariadb-password: ckV4MUd4dUJmQw==
  mariadb-root-password: VTFHOEpEd1E5TQ==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: ghost-1731881169
    meta.helm.sh/release-namespace: default
  creationTimestamp: '2024-11-17T22:06:12+00:00'
  labels:
    app: mariadb
    app.kubernetes.io/managed-by: Helm
    chart: mariadb-7.3.12
    heritage: Helm
    release: ghost-1731881169
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mariadb-password: {}
        f:mariadb-root-password: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:heritage: {}
          f:release: {}
      f:type: {}
    manager: helm
    operation: Update
    time: '2024-11-17T22:06:12+00:00'
  name: ghost-1731881169-mariadb
  namespace: default
  resourceVersion: '46037'
  uid: 717b0d7b-5775-419b-9e26-c1d120b724da
type: Opaque
